title: Andre's Website
email: andrebhu@gmail.com
description: >-
  A personal portfolio website for Andre Hu. Used to store links to projects, blog posts, and links to other media.
baseurl: ""
url: "https://bhu.dev"
# twitter_username: jekyllrb
github_username: andrebhu
permalink: /:year/:month/:title/
# Build settings
markdown: kramdown

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - run.sh
  - CNAME
