title: Andre's Website
email: andrebhu@gmail.com
description: >-
  A personal portfolio website for Andre Hu. Used to store links to projects, blog posts, and links to other media.
baseurl: ""
url: "https://bhu.dev"
github_username: andrebhu
permalink: /blog/:title

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - run.sh
  - CNAME